# Generated by Django 3.0.8 on 2021-03-14 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artworks', to='artworks.Artist'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
